[workspace]
authors = ["Matt Craig <mattwcraig@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "my-project"
platforms = ["osx-arm64", "win-64", "osx-64", "linux-64"]
version = "0.1.0"

[tasks]
hello = "echo Hello, Pixi!"
greet = { cmd = 'echo "Hello, {{ name }}!"', args = ["name"] }
print-env = "echo $MY_ENV_VAR"

[dependencies]
python = "3.13.*"
scipy = "1.15.1.*"
numpy = ">=2.3.1,<3"
fastqc = { version = ">=0.12.1,<0.13", channel = "bioconda" }
pandas = ">=2.3.0,<3"

[activation.env]
MY_ENV_VAR = "Hello, Pixi!"

[feature.test.pypi-dependencies]
pytest = { git = "https://github.com/pytest-dev/pytest", tag = "8.3.1" }

[feature.format.dependencies]
ruff = "*"

[feature.format.tasks]
fmt = "ruff --version"

[environments]
test = { features = ["test"], solve-group = "group1" }
format = { features = ["format"], no-default-feature = true }
default = { solve-group = "group1" }
